In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('train.csv')
df.head()

id  Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0   0               0.0         No                      6.0            4.0   
1   1               1.0         No                      7.0            3.0   
2   2               6.0        Yes                      1.0            0.0   
3   3               3.0         No                      7.0            3.0   
4   4               1.0         No                      4.0            4.0   

  Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
0                        No                 15.0             5.0   Extrovert  
1                        No                 10.0             8.0   Extrovert  
2                       NaN                  3.0             0.0   Introvert  
3                        No                 11.0             5.0   Extrovert  
4                        No                 13.0             NaN   Extrovert

In [10]:
df.shape

(18524, 9)

In [11]:
df2 = pd.read_csv('test.csv')
print(df2.head())

      id  Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0  18524               3.0         No                      7.0            4.0   
1  18525               NaN        Yes                      0.0            0.0   
2  18526               3.0         No                      5.0            6.0   
3  18527               3.0         No                      4.0            4.0   
4  18528               9.0        Yes                      1.0            2.0   

  Drained_after_socializing  Friends_circle_size  Post_frequency  
0                        No                  6.0             NaN  
1                       Yes                  5.0             1.0  
2                        No                 15.0             9.0  
3                        No                  5.0             6.0  
4                       Yes                  1.0             1.0  


In [12]:
df2.shape

(6175, 8)

In [13]:
X = df.iloc[:,1:-1].values # Features excluding 'id' and target variable
y = df.iloc[:,-1].values # Target variable

In [14]:
X.shape

(18524, 7)

In [15]:
print(X[:10])
print(y[:10])

[[0.0 'No' 6.0 4.0 'No' 15.0 5.0]
 [1.0 'No' 7.0 3.0 'No' 10.0 8.0]
 [6.0 'Yes' 1.0 0.0 nan 3.0 0.0]
 [3.0 'No' 7.0 3.0 'No' 11.0 5.0]
 [1.0 'No' 4.0 4.0 'No' 13.0 nan]
 [2.0 'No' 8.0 5.0 'No' nan 3.0]
 [1.0 'No' 8.0 nan 'No' nan 4.0]
 [2.0 'No' 8.0 3.0 'No' 4.0 5.0]
 [4.0 'Yes' 2.0 1.0 nan 0.0 2.0]
 [1.0 'No' 8.0 6.0 'No' 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']


In [16]:
XX = df2.iloc[:,1:].values

In [17]:
XX.shape

(6175, 7)

In [18]:
print(XX[:10])


[[3.0 'No' 7.0 4.0 'No' 6.0 nan]
 [nan 'Yes' 0.0 0.0 'Yes' 5.0 1.0]
 [3.0 'No' 5.0 6.0 'No' 15.0 9.0]
 [3.0 'No' 4.0 4.0 'No' 5.0 6.0]
 [9.0 'Yes' 1.0 2.0 'Yes' 1.0 1.0]
 [2.0 'No' 5.0 3.0 'No' 10.0 4.0]
 [3.0 'No' 4.0 5.0 'No' 15.0 5.0]
 [11.0 'Yes' 2.0 1.0 'Yes' 4.0 1.0]
 [2.0 'No' 6.0 nan 'No' 9.0 6.0]
 [8.0 nan 2.0 1.0 'Yes' 1.0 1.0]]


# Imputation

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, [0, 2, 3,5, 6]])
X[:, [0, 2, 3, 5, 6]] = imputer.transform(X[:, [0, 2, 3, 5, 6]])

In [20]:
imputer2 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, [1, 4]] = imputer2.fit_transform(X[:, [1, 4]])

In [21]:
imputer.fit(XX[:, [0, 2, 3,5, 6]])
XX[:, [0, 2, 3, 5, 6]] = imputer.transform(XX[:, [0, 2, 3, 5, 6]])
imputer2.fit(XX[:, [1, 4]])
XX[:, [1, 4]] = imputer2.transform(XX[:, [1, 4]])

In [ ]:
print(XX[:10])
print(y[:10])

[[0.0 'No' 6.0 4.0 'No' 15.0 5.0]
 [1.0 'No' 7.0 3.0 'No' 10.0 8.0]
 [6.0 'Yes' 1.0 0.0 'No' 3.0 0.0]
 [3.0 'No' 7.0 3.0 'No' 11.0 5.0]
 [1.0 'No' 4.0 4.0 'No' 13.0 4.982097334878332]
 [2.0 'No' 8.0 5.0 'No' 7.996737263880939 3.0]
 [1.0 'No' 8.0 4.044319380935631 'No' 7.996737263880939 4.0]
 [2.0 'No' 8.0 3.0 'No' 4.0 5.0]
 [4.0 'Yes' 2.0 1.0 'No' 0.0 2.0]
 [1.0 'No' 8.0 6.0 'No' 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']


# Encoding

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

encoding = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [1, 4])  # Apply to column index 2 and 5
    ],
    remainder='passthrough'
)
X = np.array(encoding.fit_transform(X))

In [112]:
print(X[:10])
print(y[:10])

[[1.0 0.0 1.0 0.0 0.0 6.0 4.0 15.0 5.0]
 [1.0 0.0 1.0 0.0 1.0 7.0 3.0 10.0 8.0]
 [0.0 1.0 1.0 0.0 6.0 1.0 0.0 3.0 0.0]
 [1.0 0.0 1.0 0.0 3.0 7.0 3.0 11.0 5.0]
 [1.0 0.0 1.0 0.0 1.0 4.0 4.0 13.0 4.982097334878332]
 [1.0 0.0 1.0 0.0 2.0 8.0 5.0 7.996737263880939 3.0]
 [1.0 0.0 1.0 0.0 1.0 8.0 4.044319380935631 7.996737263880939 4.0]
 [1.0 0.0 1.0 0.0 2.0 8.0 3.0 4.0 5.0]
 [0.0 1.0 1.0 0.0 4.0 2.0 1.0 0.0 2.0]
 [1.0 0.0 1.0 0.0 1.0 8.0 6.0 14.0 9.0]]
['Extrovert' 'Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Extrovert'
 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert']


In [113]:
# Select columns from df2 that match the features used for training (excluding 'id')
# XX_features = df2.iloc[:, 1:].values
XX = np.array(encoding.transform(XX))

In [114]:
print(XX[:10])

[[1.0 0.0 1.0 0.0 3.0 7.0 4.0 6.0 5.0289578637073005]
 [0.0 1.0 0.0 1.0 3.1168695652173914 0.0 0.0 5.0 1.0]
 [1.0 0.0 1.0 0.0 3.0 5.0 6.0 15.0 9.0]
 [1.0 0.0 1.0 0.0 3.0 4.0 4.0 5.0 6.0]
 [0.0 1.0 0.0 1.0 9.0 1.0 2.0 1.0 1.0]
 [1.0 0.0 1.0 0.0 2.0 5.0 3.0 10.0 4.0]
 [1.0 0.0 1.0 0.0 3.0 4.0 5.0 15.0 5.0]
 [0.0 1.0 0.0 1.0 11.0 2.0 1.0 4.0 1.0]
 [1.0 0.0 1.0 0.0 2.0 6.0 4.03783499737257 9.0 6.0]
 [1.0 0.0 0.0 1.0 8.0 2.0 1.0 1.0 1.0]]


In [115]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [116]:
print(y[:10])

[0 0 1 0 0 0 0 0 1 0]


In [ ]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

# Feature Scaling

In [117]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = X.copy() # 
X_train_scaled[:, 4:] = scaler.fit_transform(X[:, 4:]) 
X_test_scaled = XX.copy()
X_test_scaled[:, 4:] = scaler.transform(XX[:, 4:])

In [118]:
XX_scaled = XX.copy()
XX_scaled[:, 4:] = scaler.transform(XX[:, 4:])

In [119]:
print(X_test_scaled[:10])

[[1.0 0.0 1.0 0.0 -0.047412953605464124 0.6512014312067668
  -0.022392314457120824 -0.4868368485422638 0.016861807458252765]
 [0.0 1.0 0.0 1.0 -0.0071910233309496075 -1.9762848884989872
  -2.0433875526067093 -0.7306530267389028 -1.4328766708091063]
 [1.0 0.0 1.0 0.0 -0.047412953605464124 -0.09950894585202011
  0.9881053046176735 1.7075087552274866 1.4457604900836363]
 [1.0 0.0 1.0 0.0 -0.047412953605464124 -0.47486413438141356
  -0.022392314457120824 -0.7306530267389028 0.36627155474885775]
 [0.0 1.0 0.0 1.0 2.0175522167379127 -1.600929699969594
  -1.0328899335319153 -1.7059177395254583 -1.4328766708091063]
 [1.0 0.0 1.0 0.0 -0.39157381532936025 -0.09950894585202011
  -0.527641123994518 0.4884278642442919 -0.35338773547432784]
 [1.0 0.0 1.0 0.0 -0.047412953605464124 -0.47486413438141356
  0.48285649508027634 1.7075087552274866 0.006441909637264966]
 [0.0 1.0 0.0 1.0 2.705873940185705 -1.2255745114402004
  -1.5381387430693123 -0.9744692049355417 -1.4328766708091063]
 [1.0 0.0 1.0 0.0 -0

# Class Imbalance Check

In [120]:
from collections import Counter
print(Counter(y))

Counter({np.int64(0): 13699, np.int64(1): 4825})


In [121]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=0)
X_train_scaled_balanced, y_train_balanced = sm.fit_resample(X_train_scaled, y)
X_train_balanced, y_train_balanced = sm.fit_resample(X, y)

In [122]:
from collections import Counter
print("After SMOTE:", Counter(y_train_balanced))

After SMOTE: Counter({np.int64(0): 13699, np.int64(1): 13699})


# Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train_scaled_balanced, y_train_balanced)

LogisticRegression(random_state=0)

In [33]:
y_pred = classifier.predict(X_test_scaled)

In [34]:
y_pred_xx = classifier.predict(XX_scaled)

In [35]:
print(y_pred_xx[:10])
test_predictions = le.inverse_transform(y_pred_xx)
print(test_predictions[:10])

[0 1 0 0 1 0 0 1 0 1]
['Extrovert' 'Introvert' 'Extrovert' 'Extrovert' 'Introvert' 'Extrovert'
 'Extrovert' 'Introvert' 'Extrovert' 'Introvert']


In [36]:
# Assuming df2 has a column named "id" as its first column
ids = df2.iloc[:, 0]  # or df2['id'] if the column is named 'id'

# Create a new DataFrame for output
output_df = pd.DataFrame({
    'id': ids,
    'Personality': test_predictions
})

# Save to CSV
output_df.to_csv('submission_rafin.csv', index=False)

# Optional: preview the first few rows
print(output_df.head())

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert


# Random Forest

# Neural net

In [123]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [125]:

XX_nn = XX_scaled.astype(np.float32)
y_pred_test_nn = (model.predict(XX_nn) > 0.5).astype(int).flatten()


test_nn_predictions = le.inverse_transform(y_pred_test_nn)


output_nn_df = pd.DataFrame({
    'id': df2['id'],
    'Personality': test_nn_predictions
})


output_nn_df.to_csv('submission_nn2.csv', index=False)


print(output_nn_df.head())

193/193 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step
      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert


In [127]:
sub=pd.read_csv('submission_nn2.csv')
sub.shape

(6175, 2)